apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: elk
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      file {
        path => "/usr/share/logstash/data/pods/**/*.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"  # Prevents skipping files during testing
      }
    }
    output {
      elasticsearch {
        hosts => ["${CUSTOM_ELASTICSEARCH_HOSTS}"]
        user => "${ELASTICSEARCH_USERNAME}"
        password => "${ELASTICSEARCH_PASSWORD}"
        ssl => true
        cacert => "/usr/share/logstash/config/certs/tls.crt"
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
