apiVersion: v1
kind: Pod
metadata:
  name: data-loader
  namespace: elk
spec:
  containers:
  - name: loader
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: log-volume
      mountPath: /usr/share/logstash/logs
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: logstash-pvc

# k cp /tmp/kube-logs/pods elk/data-loader:/usr/share/logstash/logs
  