apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: elk
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: logstash-data
      mountPath: /usr/share/logstash/data
  volumes:
  - name: logstash-data
    persistentVolumeClaim:
      claimName: logstash-pvc
